import type { PlaybackState, Source, SpineStyle } from '../types';
import { time } from '../utils';
import { PlayerSlider } from './PlayerSlider';

export function NowPlaying({ state, source, selectionPending, busy, onControl, onSearch, onTools, onSources, filterActive, spineStyle, onSpineStyle }: { state?: PlaybackState; source: Source; selectionPending?: boolean; busy?: boolean; onControl: (action: string, body?: object) => void; onSearch: () => void; onTools: () => void; onSources: () => void; filterActive: boolean; spineStyle: SpineStyle; onSpineStyle: (style: SpineStyle) => void }) {
  const spotify = source === 'spotify';
  const playing = state?.transport === 'PLAYING' && !selectionPending;
  const duration = state?.durationSeconds || 1;
  return (
    <footer className="now-playing">
      <div className="now-art">{state?.artworkUrl ? <img src={state.artworkUrl} alt="" /> : <span>♪</span>}</div>
      <div className="now-copy"><strong title={state?.title}>{state?.title ?? (spotify ? 'Choose an album to play' : 'WiiM is idle')}</strong><span title={[state?.artist, state?.album].filter(Boolean).join(' · ')}>{[state?.artist, state?.album].filter(Boolean).join(' · ') || (spotify ? state?.deviceName ?? 'Choose your speaker in Devices' : 'Choose a record from the shelf')}</span>{spotify && state?.externalUrl && <a href={state.externalUrl} target="_blank" rel="noreferrer">OPEN TRACK IN SPOTIFY ↗</a>}</div>
      <div className="transport">
        <button className="transport-secondary randomise" disabled={busy || (spotify && Boolean(state?.disallows?.toggling_shuffle))} onClick={() => onControl('random')} aria-pressed={spotify ? Boolean(state?.shuffle) : undefined} aria-label={spotify ? 'Toggle Spotify shuffle' : 'Play a random track'} title={spotify ? 'Shuffle' : 'Randomise'}>{spotify ? 'SHUFFLE' : 'RANDOM'}</button>
        <button className="transport-secondary" disabled={busy || !state || state.disallows?.skipping_prev} onClick={() => onControl('previous')} aria-label="Previous track" title="Previous track">|◀</button>
        <button className="transport-primary" disabled={busy || (!state && !selectionPending) || (!selectionPending && (playing ? state?.disallows?.pausing : state?.disallows?.resuming))} onClick={() => onControl(playing ? 'pause' : 'play')} aria-label={playing ? 'Pause' : selectionPending ? 'Play selected album' : 'Play'} title={selectionPending ? 'Play selected album' : undefined}>{playing ? 'Ⅱ' : '▶'}</button>
        <button className="transport-secondary" disabled={busy || !state || state.disallows?.skipping_next} onClick={() => onControl('next')} aria-label="Next track" title="Next track">▶|</button>
      </div>
      <div className="progress"><span>{time(state?.positionSeconds ?? 0)}</span><PlayerSlider label="Track position" disabled={busy || !state?.durationSeconds || state.disallows?.seeking} max={duration} value={Math.min(duration, state?.positionSeconds ?? 0)} onCommit={(value) => onControl('seek', { positionSeconds: value })} /><span>−{time(Math.max(0, duration - (state?.positionSeconds ?? 0)))}</span></div>
      <div className="volume"><button disabled={busy || !state || state.supportsVolume === false} aria-label={state?.muted ? 'Unmute' : 'Mute'} onClick={() => onControl('mute', { muted: !state?.muted })}>{state?.muted ? '×' : '◖'}</button><PlayerSlider label="Volume" disabled={busy || !state || state.supportsVolume === false} max={100} value={state?.volume ?? 0} onCommit={(value) => onControl('volume', { volume: value })} /><span>{state?.volume ?? 0}</span></div>
      <div className="footer-tools"><button className="footer-search footer-format" onClick={() => onSpineStyle(spineStyle === 'cd' ? 'tape' : 'cd')} aria-label="Tape spine view" aria-pressed={spineStyle === 'tape'} title={spineStyle === 'cd' ? 'Switch to tape spines' : 'Switch to CD spines'}><svg viewBox="0 0 24 20" width="22" height="20" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.2">{spineStyle === 'tape' ? <><rect x="3" y="2" width="7" height="16" rx="1.5" /><rect x="14" y="2" width="7" height="16" rx="1.5" /><path d="M3 6h7M14 6h7M3 14h7M14 14h7" /></> : <><rect x="2" y="2" width="4" height="16" rx=".5" /><rect x="10" y="2" width="4" height="16" rx=".5" /><rect x="18" y="2" width="4" height="16" rx=".5" /></>}</svg><span>{spineStyle === 'cd' ? 'CDs' : 'TAPES'}</span></button><button className={`footer-search ${filterActive ? 'filtered' : ''}`} onClick={onSearch} aria-label={filterActive ? 'Edit album filter' : 'Search albums'} title="Search albums">⌕<span>{filterActive ? 'FILTER' : 'SEARCH'}</span></button><button className="footer-search" onClick={onTools} aria-label="Open crates, atmosphere and local API" title="Shelf tools">•••<span>TOOLS</span></button><button className="footer-search footer-source" onClick={onSources} aria-label="Choose music source" title={`Source: ${spotify ? 'Spotify' : 'Jellyfin'}`}>⇄<span>SOURCE</span></button></div>
    </footer>
  );
}
