import type { PlaybackState, Source, SpineStyle } from '../types';
import { nextSpineStyle } from '../spine-style';
import { time } from '../utils';
import { PlayerSlider } from './PlayerSlider';

export function NowPlaying({ state, artworkUrl, source, selectionPending, selectionReady = true, busy, onControl, onInfo, infoAvailable, onSearch, onTools, onOutputs, onSources, filterActive, spineStyle, onSpineStyle }: { state?: PlaybackState; artworkUrl?: string; source: Source; selectionPending?: boolean; selectionReady?: boolean; busy?: boolean; onControl: (action: string, body?: object) => void; onInfo: () => void; infoAvailable: boolean; onSearch: () => void; onTools: () => void; onOutputs: () => void; onSources: () => void; filterActive: boolean; spineStyle: SpineStyle; onSpineStyle: (style: SpineStyle) => void }) {
  const spotify = source === 'spotify';
  const playing = state?.transport === 'PLAYING' && !selectionPending;
  const duration = state?.durationSeconds || 1;
  const nextStyle = nextSpineStyle(spineStyle);
  const styleLabel = spineStyle === 'cd' ? 'CDs' : spineStyle === 'tape' ? 'TAPES' : 'COVERS';
  const nextStyleLabel = nextStyle === 'cd' ? 'CD spines' : nextStyle === 'tape' ? 'tapes' : 'album covers';
  return (
    <footer className="now-playing">
      <div className="now-art">{artworkUrl || state?.artworkUrl ? <img src={artworkUrl || state?.artworkUrl} alt="" decoding="async" /> : <span>♪</span>}</div>
      <div className="now-copy"><strong title={state?.title}>{state?.title ?? (spotify ? 'Choose an album to play' : `${state?.deviceName ?? 'Network player'} is idle`)}</strong><span title={[state?.artist, state?.album].filter(Boolean).join(' · ')}>{[state?.artist, state?.album].filter(Boolean).join(' · ') || (spotify ? state?.deviceName ?? 'Choose your speaker in Devices' : 'Choose a record from the shelf')}</span>{spotify && state?.externalUrl && <a href={state.externalUrl} target="_blank" rel="noreferrer">OPEN TRACK IN SPOTIFY ↗</a>}</div>
      <div className="transport">
        <button className="transport-secondary randomise" disabled={busy || (spotify && Boolean(state?.disallows?.toggling_shuffle))} onClick={() => onControl('random')} aria-pressed={spotify ? Boolean(state?.shuffle) : undefined} aria-label={spotify ? 'Toggle Spotify shuffle' : 'Play a random track'} title={spotify ? 'Shuffle' : 'Randomise'}>{spotify ? 'SHUFFLE' : 'RANDOM'}</button>
        <button className="transport-secondary" disabled={busy || !state || state.disallows?.skipping_prev} onClick={() => onControl('previous')} aria-label="Previous track" title="Previous track">|◀</button>
        <button className="transport-primary" disabled={busy || (selectionPending && !selectionReady) || (!state && !selectionPending) || (!selectionPending && (playing ? state?.disallows?.pausing : state?.disallows?.resuming))} onClick={() => onControl(playing ? 'pause' : 'play')} aria-label={playing ? 'Pause' : selectionPending && !selectionReady ? 'Album is opening' : selectionPending ? 'Play selected album' : 'Play'} title={selectionPending ? selectionReady ? 'Play selected album' : 'Album is opening' : undefined}>{playing ? 'Ⅱ' : '▶'}</button>
        <button className="transport-secondary" disabled={busy || !state || state.disallows?.skipping_next} onClick={() => onControl('next')} aria-label="Next track" title="Next track">▶|</button>
      </div>
      <div className="progress"><span>{time(state?.positionSeconds ?? 0)}</span><PlayerSlider label="Track position" disabled={busy || !state?.durationSeconds || state.disallows?.seeking} max={duration} value={Math.min(duration, state?.positionSeconds ?? 0)} onCommit={(value) => onControl('seek', { positionSeconds: value })} /><span>−{time(Math.max(0, duration - (state?.positionSeconds ?? 0)))}</span></div>
      <div className="volume"><button disabled={busy || !state || state.supportsVolume === false} aria-label={state?.muted ? 'Unmute' : 'Mute'} onClick={() => onControl('mute', { muted: !state?.muted })}>{state?.muted ? '×' : '◖'}</button><PlayerSlider label="Volume" disabled={busy || !state || state.supportsVolume === false} max={100} value={state?.volume ?? 0} onCommit={(value) => onControl('volume', { volume: value })} /><span>{state?.volume ?? 0}</span></div>
      <nav className="footer-tools" aria-label="SHELF controls"><button className="footer-search footer-info" disabled={!infoAvailable} onClick={onInfo} aria-label="Open album and song information" title="Album and song information"><b aria-hidden="true">i</b><span>INFO</span></button><button className={`footer-search ${filterActive ? 'filtered' : ''}`} onClick={onSearch} aria-label={filterActive ? 'Edit album filter' : 'Search albums'} title="Search albums">⌕<span>{filterActive ? 'FILTER' : 'SEARCH'}</span></button><button className={`footer-search footer-format footer-format-${spineStyle}`} onClick={() => onSpineStyle(nextStyle)} aria-label={`Shelf view: ${styleLabel}. Switch to ${nextStyleLabel}.`} title={`Switch to ${nextStyleLabel}`}><svg viewBox="0 0 24 20" width="20" height="18" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.2">{spineStyle === 'tape' ? <><rect x="3" y="2" width="7" height="16" rx="1.5" /><rect x="14" y="2" width="7" height="16" rx="1.5" /><path d="M3 6h7M14 6h7M3 14h7M14 14h7" /></> : spineStyle === 'covers' ? <><rect x="2" y="2" width="8" height="7" rx="1" /><rect x="14" y="2" width="8" height="7" rx="1" /><rect x="2" y="12" width="8" height="6" rx="1" /><rect x="14" y="12" width="8" height="6" rx="1" /></> : <><rect x="2" y="2" width="4" height="16" rx=".5" /><rect x="10" y="2" width="4" height="16" rx=".5" /><rect x="18" y="2" width="4" height="16" rx=".5" /></>}</svg><span>{styleLabel}</span></button><button className="footer-search" onClick={onOutputs} aria-label="Choose playback output" title="Choose playback output">◉<span>OUTPUT</span></button><button className="footer-search" onClick={onTools} aria-label="Open crates, atmosphere and local API" title="Shelf tools">•••<span>TOOLS</span></button><button className="footer-search footer-source" onClick={onSources} aria-label="Choose music source" title={`Source: ${source}`}>⇄<span>SOURCE</span></button></nav>
    </footer>
  );
}
